document.write('<form method=\"post\" action=\"/support/vote/index.php?action=vote&id=1\">');
document.write('<table border=\"0\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\">');
document.write('  <tr>');
document.write('    <td height=\"25\"><b>调查</b></td>');
document.write('  </tr>');
document.write('  <tr>');
document.write('    <td height=\"25\"><input type=\"radio\" name=\"votes[]\" value=\"1\" class=\"radio\" /> 1号</span></td>');
document.write('  </tr>');
document.write('  <tr>');
document.write('    <td height=\"25\"><input type=\"radio\" name=\"votes[]\" value=\"2\" class=\"radio\" /> 2号</span></td>');
document.write('  </tr>');
document.write('  <tr>');
document.write('    <td height=\"25\"><input type=\"radio\" name=\"votes[]\" value=\"3\" class=\"radio\" /> 3号</span></td>');
document.write('  </tr>');
document.write('  <tr>');
document.write('    <td height=\"25\"><input type=\"radio\" name=\"votes[]\" value=\"4\" class=\"radio\" /> 4号</span></td>');
document.write('  </tr>');
document.write('  <tr>');
document.write('    <td height=\"5\"></td>');
document.write('  </tr>');
document.write('  <tr>');
document.write('    <td height=\"25\"><input type=\"submit\" value=\"投票\" class=\"button\" /> <input type=\"button\" value=\"查看\" class=\"button\" onclick=\"pop_win(\'/support/vote/?type=view&id=1\', \'_blank\', 300, 300, \'yes\');\" /></td>');
document.write('  </tr>');
document.write('  <tr>');
document.write('    <td height=\"5\"></td>');
document.write('  </tr>');
document.write('</table>');
document.write('</form>');
